# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gitfs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gitfs

  target 'GitfsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitfsUITests' do
    # Pods for testing
  end

  pod 'SwiftyGif'

end
